# Generated by Django 2.1.3 on 2018-11-24 20:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='time_logged',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 24, 20, 46, 55, 487268, tzinfo=utc)),
        ),
    ]
