# Generated by Django 2.1.3 on 2018-11-26 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_coordinates_time_logged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='time_logged',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
